# Generated by Django 5.1.7 on 2025-03-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=320)),
                ("password", models.CharField(max_length=20)),
                ("aadhar", models.CharField(max_length=12)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
    ]
