# Generated by Django 5.1.7 on 2025-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_details_aadhar"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="profile_img",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
