# Generated by Django 5.1.7 on 2025-05-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_details_profile_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableRides",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("pick_up", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("hex_pick", models.CharField(max_length=8)),
                ("hex_dest", models.CharField(max_length=8)),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="conform_ride",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "avl_ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.availablerides",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="request_ride",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "avl_ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.availablerides",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehical",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=20)),
                ("ac", models.BooleanField()),
                ("seats_available", models.IntegerField()),
                ("amenities", models.TextField()),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.details",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="availablerides",
            name="vehical_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer.vehical"
            ),
        ),
    ]
