# Generated by Django 5.1.7 on 2025-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_availablerides_conform_ride_request_ride_vehical_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehical",
            name="amenities",
            field=models.TextField(null=True),
        ),
    ]
