# Generated by Django 5.1.7 on 2025-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_vehical_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehical",
            name="amenities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
