# Generated by Django 5.1.7 on 2025-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_vehical_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availablerides",
            name="hex_dest",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="availablerides",
            name="hex_pick",
            field=models.CharField(max_length=16),
        ),
    ]
