# Generated by Django 5.1.7 on 2025-05-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_availablerides_hex_dest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablerides",
            name="price",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
