# Generated by Django 5.1.7 on 2025-06-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_availablerides_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="cancel_drive",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("pick_up", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("hex_pick", models.CharField(max_length=16)),
                ("hex_dest", models.CharField(max_length=16)),
                ("price", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.details",
                    ),
                ),
                (
                    "vehical_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.vehical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cancel_ride",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "avl_ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.availablerides",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.details",
                    ),
                ),
            ],
        ),
    ]
