# Generated by Django 5.1.7 on 2025-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_cancel_drive_cancel_ride"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablerides",
            name="remain_seats",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
