# Generated by Django 5.1.7 on 2025-06-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_availablerides_remain_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehical",
            name="color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehical",
            name="number_plate",
            field=models.TextField(blank=True, null=True),
        ),
    ]
