# Generated by Django 5.1.7 on 2025-06-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_vehical_color_vehical_number_plate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="availablerides",
            unique_together={("u_id", "date", "pick_up", "destination")},
        ),
    ]
